import {Store} from './store';

export const SmythsToys: Store = {
  backoffStatusCodes: [403],
  currency: '£',
  labels: {
    inStock: {
      container: '#addToCartButton',
      text: ['add to basket'],
    },
    maxPrice: {
      container: '.price_tag',
      euroFormat: false,
    },
    outOfStock: {
      container: '.instoreMessage',
      text: ['out of stock'],
    },
  },
  links: [
    {
      brand: 'pokemon',
      model: 'booster',
      description: "Battle Styles Booster",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197254.jpg',
      series: 'battle-styles',
      url:
        'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-sword-and-shield-5-battle-styles-booster-pack-assortment/p/197254',
    },
    {
      brand: 'pokemon',
      model: 'booster',
      description: "Vivid Voltage Booster",
      thumbnail: 'https://image.smythstoys.com/original/desktop/192754.jpg',
      series: 'vivid-voltage',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-booster-sword-and-shield-series-4-vivid-voltage/p/192754',
    },
    {
      brand: 'pokemon',
      model: 'triple-booster',
      description: "Vivid Voltage Triple Booster",
      thumbnail: 'https://image.smythstoys.com/original/desktop/191580.jpg',
      series: 'vivid-voltage',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-tcg-sword-and-shield-vivid-voltage-three-booster-blister-assortment/p/191580',
    },
    {
      brand: 'pokemon',
      model: 'tin',
      description: "Hidden Fates Tin",
      thumbnail: 'https://image.smythstoys.com/original/desktop/179756.jpg',
      series: 'hidden-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-hidden-fates-tin-assortment/p/179756',
    },
    {
      brand: 'pokemon',
      model: 'etb',
      description: "Hidden Fates ETB",
      thumbnail: 'https://image.smythstoys.com/original/desktop/181461.jpg',
      series: 'hidden-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-hidden-fates-elite-trainer-box/p/181461',
    },
    {
      brand: 'pokemon',
      model: 'etb',
      description: "Zacian/Zamazenta Elite Trainer Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/192757.jpg',
      series: 'sword-and-shield',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-sword-and-shield-elite-trainer-box-plus-assortment/p/192757',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Ultra-Premium Collection",
      thumbnail: 'https://image.smythstoys.com/original/desktop/194705.jpg',
      series: 'sword-and-shield',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-tcg-sword-and-shield-ultra-premium-collection-zacian-and-zamazenta/p/194705',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Venusaur/Blastoise VMAX Battle Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197417.jpg',
      series: 'sword-and-shield',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-tcg-venusaur-blastoise-vmax-battle-box-assortment/p/197417',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Galarian Rapidash V Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197414.jpg',
      series: 'sword-and-shield',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-galarian-rapidash-v-box/p/197414',
    },
    {
      brand: 'pokemon',
      model: 'mini-tin',
      description: "Shining Fates Mini Tin",
      thumbnail: 'https://image.smythstoys.com/original/desktop/196811.jpg',
      series: 'shining-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-shining-fates-mini-tin-assortment-styles-vary/p/196811',
    },
    {
      brand: 'pokemon',
      model: 'etb',
      description: "Elite Trainer Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/196815.jpg',
      series: 'shining-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-shining-fates-elite-trainer-box/p/196815',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Mad Party Pin Collection",
      thumbnail: 'https://image.smythstoys.com/original/desktop/196817.jpg',
      series: 'shining-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-shining-fates-mad-party-pin-collection-assortment-styles-vary/p/196817',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Premium Collection",
      thumbnail: 'https://image.smythstoys.com/original/desktop/196812.jpg',
      series: 'shining-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-shining-fates-premium-collection-assortment-shiny-crobat-shiny-dragapult/p/196812',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Pikachu V Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/196816.jpg',
      series: 'shining-fates',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-shining-fates-pikachu-v-box/p/196816',
    },
    {
      brand: 'pokemon',
      model: 'triple-booster',
      description: "Battle Styles 3-Pack Booster",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197259.jpg',
      series: 'battle-styles',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-sword-and-shield-5-battle-styles-3-pack-booster-assortment/p/197259',
    },
    {
      brand: 'pokemon',
      model: 'box',
      description: "Urshifu V Box",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197255.jpg',
      series: 'battle-styles',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-single-rapid-strike-urshifu-v-box-assortment/p/197255',
    },
    {
      brand: 'pokemon',
      model: 'tin',
      description: "V Strikers Tin",
      thumbnail: 'https://image.smythstoys.com/original/desktop/197413.jpg',
      series: 'battle-styles',
      url: 'https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-cards-game/pok%c3%a9mon-trading-card-game-v-strikers-tin-tyranitar-v-empoleon-v-assortment/p/197413',
    },
  ],
  name: 'Smyths Toys',
  postage: 0,
};
